version: 2
jobs:
  build:
    docker: &docker
      - image: ruby:2.4.1-alpine
    working_directory: /work
    branches:
      only:
        - circleci-2.0
    steps:
      - run: &setup_requirements
          name: Install System Dependencies
          command: |
            # See also https://circleci.com/docs/2.0/custom-images/#adding-required-and-custom-tools-or-files
            apk add --update --no-cache git openssh-client tar gzip ca-certificates \
              tzdata
            gem install -N bundler
      - run: &set_timezone
          name: Set timezone to Asia/Tokyo
          command: cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      - checkout
      - restore_cache: &restore_gems_cache
          name: Restore bundler cache
          keys:
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Install Ruby Dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3
            bundle clean
      - save_cache: &save_gems_cache
          name: Save bundler cache
          key: gems-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle
      - add_ssh_keys:
          fingerprints:
            # for ssh to masutaka.net
            # See https://circleci.com/gh/masutaka/masutaka-metrics/edit#ssh
            - "a3:d5:cc:2d:b5:d3:ad:19:f2:50:5f:61:34:f4:35:74"
      - deploy:
          command: .circleci/deploy-circleci.sh
